#
###################################
# Site wide configuration
####################################
#
title: Felipe Gentil
email: cdigentil@gmail.com
url: https://fpgentil.github.io/ # the base hostname & protocol for your site
keywords: ["Programming", "Ruby"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Brasilia
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Felipe Gentil
  avatar: fpgentil.jpg
  job: "Ruby Developer"
  bio: "Drinks coffee in the morning, beer at night and writes code throughout the day!"
  email: cdigentil@gmail.com
  disqus-shortname: felipegentil
  twitter: fpgentil
  facebook: fpgentil
  google:
    plus: #username
    analytics: UA-62251910-2
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: fpgentil #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: felipepelizarogentil #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
