name: Felipe Pelizaro Gentil
description: Soccer · Beer · Code
meta_description: "Your New Jekyll Site, Blogging about stuffs"

aboutPage: true

markdown: kramdown
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://fpgentil.github.io'
google_analytics: 'UA-66102494-1'
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://fpgentil.github.io'
author:         'Felipe Pelizaro Gentil'
authorTwitter:  'fpgentil'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
