# Site settings
title: Felipe Pelizaro Gentil
email: cdigentil@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ruby on Rails developer at Walmart.com and Kiskadi.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fpgentil.github.io" # the base hostname & protocol for your site
twitter_username: fpgentil
github_username:  fpgentil

# Build settings
markdown: kramdown
